### ISSUE TITLE
[Bug] Default honor isn't currect

### ISSUE THREAD

**Issue by eddiesky1428** [qq88976321/gbf-beautify-honors-web#11]
Default honor of "Meat Beast EX (0 button)" is 50578, but this time is 50577.
![278299](https://github.com/qq88976321/gbf-beautify-honors-web/assets/126105116/2e6c2cc6-6464-4c40-8739-3f1dc18df642)

**Comment by qq88976321** [comment]
Thanks for the report. I have fixed the default value. 

You may need to reset the default value or change the value manually, as this project caches all information in browser's local storage. 

I will pay attention to whether this value changes again during the next GW.
